// Re-export all types from schemas
export type {
  LanguageCode,
  LevelCode,
  InputType,
  NodeStatus,
  WeaknessType,
  GrammaticalRole,
  JanusCell,
  JanusColumn,
  JanusMatrix,
  JanusCombination,
  JanusProgress,
  IntoningProgress,
  Variation,
  ClozeOption,
  Phrase,
  MiniTask,
  Matrix,
  World,
  ComprehensionOption,
  ComprehensionQuestion,
  InputContent,
  InputStats,
  InputEvent,
  LevelInfo,
  GamificationState,
  WorldProgress,
  UserProgress,
  Vocabulary,
  VocabularyOption,
  ShardDetection,
  ShardDetectionShard,
  PragmaStrike,
  PragmaStrikeOption,
  ResonancePath,
  EchoStream,
  EchoStreamPowerWord,
  GlyphWeaving,
  GlyphWeavingGlyph,
  GlyphWeavingPattern,
  BlockComponent,
  ConversationalBlock,
  BlockBuilder,
  BlockSwap,
  BlockEcho,
  LessonContent,
  LessonMode,
  AudioTag,
  CulturalNote,
  SurvivalStrategy,
  CommonError,
} from '@/schemas/content';

// Re-export topic tree types
export type {
  TopicLeaf,
  TopicBranch,
  TopicTree,
  TreeProgress,
} from '@/schemas/topicTree';

// Re-export schemas for validation
export {
  LanguageCodeSchema,
  LevelCodeSchema,
  InputTypeSchema,
  NodeStatusSchema,
  WeaknessTypeSchema,
  GrammaticalRoleSchema,
  JanusCellSchema,
  JanusColumnSchema,
  JanusMatrixSchema,
  JanusCombinationSchema,
  JanusProgressSchema,
  IntoningProgressSchema,
  VariationSchema,
  ClozeOptionSchema,
  PhraseSchema,
  MiniTaskSchema,
  MatrixSchema,
  WorldSchema,
  ComprehensionOptionSchema,
  ComprehensionQuestionSchema,
  InputContentSchema,
  InputStatsSchema,
  InputEventSchema,
  LevelInfoSchema,
  GamificationStateSchema,
  WorldProgressSchema,
  UserProgressSchema,
  VocabularySchema,
  ShardDetectionSchema,
  PragmaStrikeSchema,
  ResonancePathSchema,
  EchoStreamSchema,
  GlyphWeavingSchema,
  BlockComponentSchema,
  ConversationalBlockSchema,
  BlockBuilderSchema,
  BlockSwapSchema,
  BlockEchoSchema,
  LessonContentSchema,
  AudioTagSchema,
  CulturalNoteSchema,
  SurvivalStrategySchema,
  CommonErrorSchema,
} from '@/schemas/content';

// Re-export topic tree schemas
export {
  TopicLeafSchema,
  TopicBranchSchema,
  TopicTreeSchema,
  TreeProgressSchema,
} from '@/schemas/topicTree';

// Re-export constants
export {
  SUPPORTED_LANGUAGES,
  SUPPORTED_LEVELS,
  INPUT_TYPES,
  NODE_STATUSES,
  GRAMMATICAL_ROLES,
  LEVEL_THRESHOLDS,
  XP_RULES,
  COIN_RULES,
  GEM_RULES,
  USER_LEVELS,
  JANUS_CONFIG,
  SHADOWING_CONFIG,
  INPUT_CONFIG,
  MINITASK_CONFIG,
  STREAK_CONFIG,
  APP_COLORS,
  BRANCH_COLORS,
  HUNTER_RANKS,
  RANK_UNLOCK_RULES,
  getLevelByXP,
  getXPToNextLevel,
  getLevelProgress,
  getRankByXP,
  getRankProgress,
  canAccessContent,
} from '@/lib/constants';

export type {
  SupportedLanguage,
  SupportedLevel,
  HunterRank,
  HunterRankInfo,
} from '@/lib/constants';

// Re-export SRS types
export type {
  ReviewResponse,
  ContentSourceType,
  CardStatus,
  ContentSource,
  ReviewHistoryEntry,
  SRSCard,
  SRSStats,
  CreateSRSCardInput,
  ReviewSessionResult,
  TranscriptPhrase,
  Transcript,
  DetectedWord,
  SRSConfig,
} from './srs';

export {
  ReviewResponseValues,
  ContentSourceTypeValues,
  CardStatusValues,
  ContentSourceSchema,
  ReviewHistoryEntrySchema,
  SRSCardSchema,
  SRSStatsSchema,
  CreateSRSCardInputSchema,
  ReviewSessionResultSchema,
  TranscriptPhraseSchema,
  TranscriptSchema,
  DetectedWordSchema,
  SRS_CONFIG,
} from './srs';
